Repository oxidecomputer/design-system, pull requests merged in 2024-12, with the labels that each got.

#93 Tweak content default
  styles/dist/blue.css
  styles/dist/green.css
  styles/dist/main.css
  styles/dist/purple.css
  styles/dist/red.css
  styles/dist/tailwind-tokens.js
  styles/dist/yellow.css
  styles/src/tokens.json
Labels: minor

#53 Allow `.tsx` imports
  package.json
  tsconfig.json
Labels: skip-release

#95 Upgrade node to LTS
  .github/workflows/build-themes.yaml
  .github/workflows/check-release.yml
  .github/workflows/release.yml
  .github/workflows/update-icons.yaml
Labels: skip-release

#96 Remove `update-icons` CI
  .github/workflows/update-icons.yaml
  README.md
Labels: skip-release

#92 Add convenience classes for inline code and links
  components/src/assets/asciidoc.css
Labels: patch

#97 Switch `tailwind-tokens.js` from cjs to esm
  package.json
  scripts/convert-tokens.ts
Labels: patch

#99 Remove color boost for AsciiDoc body text
  components/src/assets/asciidoc.css
Labels: patch

#101 Make asciidoc summary title brighter
  components/src/assets/asciidoc.css
Labels: patch

#100 Reusable AsciiDoc utils
  .licenserc.yaml
  components/src/asciidoc/Section.tsx
  components/src/asciidoc/TableOfContents.tsx
  components/src/asciidoc/index.tsx
  components/src/asciidoc/langs/oxql.tmLanguage.json
  components/src/asciidoc/oxide-dark.json
  components/src/asciidoc/use-delegated-links.ts
  components/src/asciidoc/util.ts
  components/src/assets/asciidoc.css
  package-lock.json
  package.json
  test/renderWithBreaks.test.ts
  test/vitest.config.ts
Labels: minor

#102 Shared link and code styles
  components/src/asciidoc/TableOfContents.tsx
  components/src/assets/asciidoc.css
Labels: patch

#103 Tweak code size to use `em` not `rem`
  components/src/assets/asciidoc.css
Labels: patch

#104 Move dev deps to dev deps, remove some unneeded deps
  package-lock.json
  package.json
Labels: patch
