Repository oxidecomputer/design-system, pull requests merged in 2025-01, with the labels that each got.

#105 Table title tweaks
  components/src/assets/asciidoc.css
Labels: patch

#107 Update remix peer-dependency
  package-lock.json
  package.json
Labels: major

#106 Don't depend on React Router or Remix directly
  components/src/asciidoc/TableOfContents.tsx
  components/src/asciidoc/use-delegated-links.ts
  package-lock.json
  package.json
Labels: minor

#116 Print style improvements
  components/src/assets/asciidoc.css
Labels: minor
